import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { auth } from "@/auth";
import { SessionProvider } from "next-auth/react";
import NavComponent from "@/components/nav/NavComponent";
import RoleSelection from "@/components/auth/RoleSelection";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const interFont = Inter({
  subsets: ["latin"],
  weight: ["400", "600", "700", "900"],
  variable: "--my-font-family",
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  if (session?.user?.isOAuth && !session?.user?.role) {
    return (
      <html lang="en">
        <body
          className={`${interFont.variable} bg-bgLight flex items-center justify-center  min-h-full sm:h-[calc(100svh-59.2px)] sm:min-h-0`}
        >
          <SessionProvider session={session}>
            <RoleSelection />
          </SessionProvider>
        </body>
      </html>
    );
  }

  return (
    <html lang="en">
      <body className={`${interFont.variable} bg-bgLight `}>
        <SessionProvider session={session}>
          <NavComponent />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
